"use client";

import { useEffect, useMemo, useState } from "react";

import Header from "@/components/Header";
import { ImageIcon, LoadingIcon, MusicIcon, SparklesIcon } from "@/components/Icons";

type MediaItem = { kind: "song" | "video" | "image"; jobId: string; title: string; createdAt: number; status: "pending" | "processing" | "done" | "error"; progress?: number; ready: boolean; mediaUrl?: string; downloadUrl?: string; studioUrl?: string };
type AccountData = { configured: boolean; authenticated: boolean; email?: string; media?: MediaItem[]; subscription?: null | { planName: string; songsRemaining: number; editsRemaining: number; renewsAt: number; cancelAtPeriodEnd: boolean } };

export default function AccountDashboard() {
  const [data, setData] = useState<AccountData | null>(null);
  const [filter, setFilter] = useState<"all" | MediaItem["kind"]>("all");
  useEffect(() => { void fetch("/api/account", { cache: "no-store" }).then((response) => response.json()).then(setData).catch(() => setData({ configured: true, authenticated: false })); }, []);
  const items = useMemo(() => (data?.media ?? []).filter((item) => filter === "all" || item.kind === filter), [data?.media, filter]);
  if (!data) return <Shell><div className="flex min-h-[65vh] items-center justify-center text-violet-200"><LoadingIcon className="animate-spin" /></div></Shell>;
  if (!data.authenticated) return <Shell><section className="mx-auto max-w-3xl py-16 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-violet-500/15 text-violet-200"><SparklesIcon /></div><h1 className="mt-6 text-4xl font-semibold">Dein persönlicher Bereich</h1><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-zinc-400">Melde dich an oder registriere dich kostenlos, damit dein Abo und alle neuen Songs, Videos und Bilder dauerhaft gespeichert werden.</p><a href="/anmelden?next=/konto" className="mt-7 inline-flex rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-600 px-6 py-3 text-sm font-semibold">Anmelden oder registrieren</a>{!data.configured && <p className="mt-4 text-xs text-amber-300">Die Kundenanmeldung wird gerade eingerichtet.</p>}</section></Shell>;
  return <Shell>
    <section className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-400/10 px-3 py-1.5 text-xs text-violet-200">Mein KI Studio</div><h1 className="mt-4 text-4xl font-semibold tracking-[-0.04em]">Meine Inhalte</h1><p className="mt-2 text-sm text-zinc-500">{data.email}</p></div><form action="/api/auth/signout" method="post"><button className="rounded-xl border border-white/10 px-4 py-2.5 text-xs text-zinc-300">Abmelden</button></form></section>
    <section className="mt-8 rounded-3xl border border-fuchsia-400/20 bg-gradient-to-r from-fuchsia-500/[0.1] to-violet-500/[0.05] p-6">{data.subscription ? <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-fuchsia-300">Song-Abo aktiv</p><h2 className="mt-2 text-2xl font-semibold">{data.subscription.planName}</h2><p className="mt-2 text-sm text-zinc-400"><strong className="text-white">{data.subscription.songsRemaining}</strong> Songs · <strong className="text-white">{data.subscription.editsRemaining}</strong> KI-Bearbeitungen übrig</p><p className="mt-1 text-[11px] text-zinc-500">{data.subscription.cancelAtPeriodEnd ? "Endet" : "Neues Kontingent"} am {new Date(data.subscription.renewsAt).toLocaleDateString("de-DE")}</p></div><button type="button" onClick={() => void fetch("/api/song-subscription-portal", { method: "POST" }).then((response) => response.json()).then((value) => { if (value.url) window.location.href = value.url; })} className="rounded-xl border border-white/10 px-4 py-3 text-xs font-semibold">Abo verwalten</button></div> : <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-lg font-semibold">Noch kein Song-Abo</p><p className="mt-1 text-sm text-zinc-400">Wähle ein Paket und nutze das vollständige Sound Studio.</p></div><a href="/ki-song-erstellen#song-abos" className="rounded-xl bg-fuchsia-600 px-4 py-3 text-xs font-semibold">Abos ansehen</a></div>}</section>
    <section className="mt-10"><div className="flex flex-wrap gap-2">{(["all", "song", "video", "image"] as const).map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-xl px-4 py-2 text-xs font-semibold ${filter === value ? "bg-violet-600 text-white" : "border border-white/10 text-zinc-400"}`}>{value === "all" ? "Alle" : value === "song" ? "Songs" : value === "video" ? "Videos" : "Bilder"}</button>)}</div>
      {items.length === 0 ? <div className="mt-6 rounded-3xl border border-dashed border-white/10 bg-white/[0.025] p-10 text-center"><p className="text-lg font-semibold">Noch keine Inhalte gespeichert</p><p className="mt-2 text-sm text-zinc-500">Neue Bestellungen erscheinen nach der Zahlung automatisch hier.</p><a href="/" className="mt-5 inline-flex text-sm font-semibold text-violet-300">Jetzt etwas erstellen →</a></div> : <div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <MediaCard key={`${item.kind}:${item.jobId}`} item={item} />)}</div>}
    </section>
  </Shell>;
}

function MediaCard({ item }: { item: MediaItem }) { const working = item.status === "pending" || item.status === "processing"; return <article className="overflow-hidden rounded-3xl border border-white/10 bg-white/[0.035]"><div className="flex aspect-video items-center justify-center bg-black/30">{item.ready && item.kind === "image" ? <img src={item.mediaUrl} alt={item.title} className="h-full w-full object-cover" /> : item.ready && item.kind === "video" ? <video src={item.mediaUrl} controls preload="metadata" className="h-full w-full object-contain" /> : item.ready && item.kind === "song" ? <div className="w-full px-6 text-center"><MusicIcon className="mx-auto text-fuchsia-300" /><audio src={item.mediaUrl} controls preload="metadata" className="mt-4 w-full" /></div> : <div className="text-center text-zinc-500">{working ? <LoadingIcon className="mx-auto animate-spin" /> : item.kind === "image" ? <ImageIcon className="mx-auto" /> : <MusicIcon className="mx-auto" />}<p className="mt-3 text-xs">{working ? `${item.progress ?? 0} % erstellt` : "Erstellung unterbrochen"}</p></div>}</div><div className="p-5"><div className="flex items-center justify-between gap-3"><span className="text-[10px] font-semibold uppercase tracking-wider text-violet-300">{item.kind === "song" ? "Song" : item.kind === "video" ? "Video" : "Bild"}</span><span className="text-[10px] text-zinc-600">{new Date(item.createdAt).toLocaleDateString("de-DE")}</span></div><h3 className="mt-2 truncate font-semibold">{item.title}</h3><div className="mt-4 flex flex-wrap gap-2">{item.downloadUrl && <a href={item.downloadUrl} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-zinc-200">Herunterladen</a>}{item.studioUrl && <a href={item.studioUrl} className="rounded-lg bg-fuchsia-600 px-3 py-2 text-xs font-semibold">Sound Studio</a>}</div></div></article>; }
function Shell({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-[#07070b] text-white"><Header active="account" /><div className="mx-auto max-w-7xl px-5 pb-20 pt-12 sm:px-8">{children}</div></main>; }
