"use client";
import { uploadPresigned } from '@vercel/blob/client';
import { useEffect,useRef,useState } from 'react';
import Header from './Header';
import Link from 'next/link';
type Job={id:string;status:string;target:string;duration:number;quotaSeconds?:number;error?:string;qualityWarning?:string};
type Access={configured:boolean;authenticated:boolean;owner?:boolean;subscription?:boolean;videoSecondsRemaining?:number|null;studioEditsRemaining?:number|null;jobs?:Job[]};
const safe=(name:string)=>name.replace(/[^a-zA-Z0-9._-]+/g,'-').slice(-100)||'datei';
export default function CharacterSwap(){
 const [video,setVideo]=useState<File|null>(null),[reference,setReference]=useState<File|null>(null),[videoUrl,setVideoUrl]=useState(''),[imageUrl,setImageUrl]=useState(''),[target,setTarget]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[job,setJob]=useState<Job|null>(null),[jobs,setJobs]=useState<Job[]>([]),[access,setAccess]=useState<Access|null>(null),[duration,setDuration]=useState(0),[progress,setProgress]=useState(0);
 const validDuration=Number.isFinite(duration)&&duration>=2&&duration<=30,quotaSeconds=Math.ceil(duration*3),original=useRef<HTMLVideoElement>(null),result=useRef<HTMLVideoElement>(null);
 useEffect(()=>{if(!video){setVideoUrl('');return;}const url=URL.createObjectURL(video);setVideoUrl(url);return()=>URL.revokeObjectURL(url);},[video]);
 useEffect(()=>{if(!reference){setImageUrl('');return;}const url=URL.createObjectURL(reference);setImageUrl(url);return()=>URL.revokeObjectURL(url);},[reference]);
 useEffect(()=>{fetch('/api/character-swap',{cache:'no-store'}).then(r=>r.json()).then((data:Access)=>{setAccess(data);setJobs(data.jobs||[]);const id=localStorage.getItem('character-swap-job');const saved=(data.jobs||[]).find(item=>item.id===id);if(saved)setJob(saved);}).catch(()=>setAccess({configured:false,authenticated:false}));},[]);
 useEffect(()=>{if(job?.status!=='processing')return;let disposed=false;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const response=await fetch(`/api/character-swap?id=${encodeURIComponent(job.id)}`,{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error);if(!disposed){setJob(data);setJobs(current=>current.map(item=>item.id===data.id?data:item));setError('');}}catch{if(!disposed)setError('Verbindung unterbrochen. Der vorhandene Auftrag wird weiter abgefragt.');}if(!disposed)timer=setTimeout(poll,8000);};timer=setTimeout(poll,4000);return()=>{disposed=true;clearTimeout(timer);};},[job?.id,job?.status]);
 async function start(){if(!video||busy)return;setBusy(true);setProgress(0);setError('');try{
  const base=`character-swap/upload/${Date.now()}`;
  const videoBlob=await uploadPresigned(`${base}/video-${safe(video.name)}`,video,{access:'private',handleUploadUrl:'/api/upload-character-swap',multipart:true,contentType:video.type,onUploadProgress:({percentage})=>setProgress(Math.round(percentage*.8))});
  const imageBlob=reference?await uploadPresigned(`${base}/reference-${safe(reference.name)}`,reference,{access:'private',handleUploadUrl:'/api/upload-character-swap',contentType:reference.type,onUploadProgress:({percentage})=>setProgress(80+Math.round(percentage*.1))}):null;
  const response=await fetch('/api/character-swap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({videoUri:`blob:${videoBlob.pathname}`,videoType:video.type,imageUri:imageBlob?`blob:${imageBlob.pathname}`:undefined,imageType:reference?.type,target,consent:confirmed})}),body=await response.json();if(response.status===401){window.location.href='/anmelden?next=/charakter-tauschen';return;}if(!response.ok)throw new Error(body.error);setProgress(100);setJob(body);setJobs(current=>[body,...current.filter(item=>item.id!==body.id)]);localStorage.setItem('character-swap-job',body.id);
 }catch(reason){setError(reason instanceof Error?reason.message:'Start fehlgeschlagen.');}finally{setBusy(false);}}
 const allowed=Boolean(access?.owner||access?.subscription);
 return <main className="min-h-screen bg-[#101110] text-[#f7f4ef]"><Header/><div className="mx-auto max-w-6xl px-6 py-12"><Link href="/video-studio" className="text-sm text-[#dfba83]">← Video Studio</Link><p className="mt-10 text-xs tracking-[.22em] text-[#dfba83]">CHARAKTER STUDIO · RUNWAY ALEPH 2.0</p><h1 className="mt-4 text-4xl font-medium tracking-tight sm:text-6xl">Dein ganzes Video.<br/><span className="font-serif italic text-[#dfba83]">Neue Charaktere.</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-zinc-400">Verändere Personen frei über alle vorhandenen Szenen. Schnittfolge, Kamera, Bildformat und Originalton sollen erhalten bleiben. KI-Ergebnisse können dennoch sichtbar abweichen.</p>
 <div className="mt-10 grid gap-8 lg:grid-cols-2"><section className="space-y-6 rounded-2xl border border-white/10 bg-white/[.025] p-6"><h2 className="text-xl">01 · Dein Ausgangsmaterial</h2><label className="block text-sm">Originalvideo <span className="text-zinc-500">· MP4 / MOV, maximal 40 MB</span><input type="file" accept="video/mp4,video/quicktime" className="mt-3 block w-full text-xs file:mr-3 file:rounded-lg file:border-0 file:bg-[#dfba83] file:px-4 file:py-3 file:text-black" onChange={e=>{setVideo(e.target.files?.[0]||null);setDuration(0);setConfirmed(false);setJob(null);}}/></label><p className="text-xs leading-6 text-zinc-500">2–30 Sekunden, mehrere Szenen und Schnitte, bis Full HD. Höhere Bildraten werden auf 30 Bilder pro Sekunde angepasst.</p>{videoUrl&&<video controls preload="metadata" src={videoUrl} onLoadedMetadata={e=>setDuration(e.currentTarget.duration)} className="max-h-72 w-full rounded-xl bg-black"/>}<label className="block text-sm">Bearbeitetes Startbild <span className="text-zinc-500">· optional, maximal 5 MB</span><input type="file" accept="image/png,image/jpeg,image/webp" className="mt-3 block w-full text-xs" onChange={e=>setReference(e.target.files?.[0]||null)}/></label>{imageUrl&&<div className="flex items-center gap-4"><img src={imageUrl} alt="Optionales bearbeitetes Startbild" className="h-28 w-28 rounded-xl object-cover"/><button onClick={()=>setReference(null)} className="text-xs text-[#dfba83]">Ohne Bild fortfahren</button></div>}</section>
 <section className="space-y-6 rounded-2xl border border-white/10 bg-white/[.025] p-6"><h2 className="text-xl">02 · Was soll sich ändern?</h2><label className="block text-sm" htmlFor="swap-description">Beschreibe die neuen Personen</label><textarea id="swap-description" value={target} onChange={e=>setTarget(e.target.value)} maxLength={1000} rows={6} placeholder="Zum Beispiel: Ändere alle Personen zu türkischen Charakteren. Bewegungen, Kamera und Umgebung beibehalten." className="w-full rounded-xl border border-white/15 bg-black/30 p-4 text-sm leading-7 outline-none focus:border-[#dfba83]"/><div className="flex flex-wrap gap-2">{['Ändere die Personen zu türkischen Charakteren.','Ersetze die Person durch eine futuristische Figur.','Verändere nur Kleidung und Frisur der Person.'].map(text=><button key={text} onClick={()=>setTarget(text)} className="rounded-lg border border-white/10 px-3 py-2 text-left text-xs text-zinc-400 hover:border-[#dfba83]">{text}</button>)}</div><p className="text-xs leading-6 text-zinc-500">Das optionale Bild muss den bereits bearbeiteten ersten Frame zeigen. Ein einzelnes Porträt ist dafür ungeeignet.</p>
 <div className="rounded-xl border border-[#dfba83]/20 bg-[#dfba83]/5 p-4"><p className="text-sm text-[#dfba83]">{access?.owner?'Kostenloses Inhaber-Testkonto':validDuration?`${quotaSeconds} Video-Sekunden + 1 Studio-Export`:'Im Video-Abo enthalten'}</p><p className="mt-2 text-xs leading-6 text-zinc-400">{access?.owner?'Für info@kivideostudio.de wird kein Kontingent berechnet.':validDuration?`${duration.toFixed(2).replace('.',',')} Sekunden werden wegen der Aleph-Rechenkosten dreifach auf das Videokontingent angerechnet.`:'Wähle ein Video für die genaue Abrechnung.'}</p>{!access?.owner&&access?.subscription&&<p className="mt-2 text-xs text-zinc-500">Verfügbar: {access.videoSecondsRemaining} Video-Sekunden · {access.studioEditsRemaining} Exporte</p>}</div>
 {!access?.authenticated?<Link href="/anmelden?next=/charakter-tauschen" className="block rounded-xl border border-[#dfba83]/30 p-4 text-center text-sm text-[#dfba83]">Anmelden und Charakter Studio öffnen</Link>:!allowed?<Link href="/ki-video-erstellen#video-abos" className="block rounded-xl border border-[#dfba83]/30 p-4 text-center text-sm text-[#dfba83]">Video-Abo auswählen · ab 34,99 € monatlich</Link>:null}
 <label className="flex gap-3 text-xs leading-6 text-zinc-400"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1 accent-[#dfba83]"/>Ich darf dieses Material verwenden und möchte es zur Bearbeitung an Runway senden. Jede neue Generierung wird erneut auf mein Kontingent angerechnet.</label>{access?.configured===false&&<p className="text-sm text-amber-200">Die KI-Verbindung ist vorübergehend nicht verfügbar.</p>}<button disabled={!video||!validDuration||target.trim().length<5||!confirmed||busy||job?.status==='processing'||access?.configured!==true||!allowed} onClick={()=>void start()} className="w-full rounded-xl bg-[#dfba83] px-5 py-4 text-sm font-semibold text-black disabled:cursor-not-allowed disabled:opacity-40">{busy?`Video wird übertragen … ${progress}%`:job?.status==='processing'?'Charaktere werden bearbeitet …':'Charaktere jetzt verändern'}</button><p role="status" className="text-sm text-amber-200">{error||job?.error}</p></section></div>
 {job&&<section className="mt-10 rounded-2xl border border-white/10 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-2xl">Original & neue Version</h2><p className="text-sm text-[#dfba83]">{job.status==='done'?(job.qualityWarning?'Bitte Abweichungen prüfen':'Bereit zum Vergleichen'):job.status==='processing'?'In Bearbeitung · Du kannst später zurückkommen':job.status==='error'?'Bearbeitung fehlgeschlagen':'Start wird geprüft'}</p></div><p className="my-4 text-sm text-zinc-400">{job.target}</p>{job.qualityWarning&&<p role="status" className="mb-5 rounded-xl border border-amber-300/20 bg-amber-300/10 p-4 text-sm leading-6 text-amber-200">{job.qualityWarning}</p>}{job.status==='done'&&<><div className="grid gap-5 sm:grid-cols-2"><div><p className="mb-2 text-xs text-zinc-500">ORIGINAL</p><video ref={original} src={`/api/character-swap?id=${job.id}&asset=original`} controls className="max-h-96 w-full bg-black"/></div><div><p className="mb-2 text-xs text-zinc-500">NEUE VERSION</p><video ref={result} src={`/api/character-swap?id=${job.id}&asset=result`} controls className="max-h-96 w-full bg-black"/></div></div><div className="mt-5 flex flex-wrap gap-5 text-sm text-[#dfba83]"><button onClick={()=>{if(original.current&&result.current){original.current.currentTime=0;result.current.currentTime=0;result.current.muted=true;void Promise.allSettled([original.current.play(),result.current.play()]);}}}>Beide von Anfang abspielen</button><a href={`/api/character-swap?id=${job.id}&asset=result&download=1`}>Video herunterladen ↓</a></div></>}</section>}
 {jobs.length>0&&<section className="mt-10"><h2 className="text-xl">Meine Bearbeitungen</h2><div className="mt-4 flex flex-wrap gap-3">{jobs.map(item=><button key={item.id} onClick={()=>{setJob(item);localStorage.setItem('character-swap-job',item.id);}} className="max-w-xs truncate rounded-xl border border-white/15 px-4 py-3 text-sm text-zinc-400">{item.target}</button>)}</div></section>}</div></main>;
}
